services:
  _defaults:
    autoconfigure: true

  tdoescher\GooglemapsBundle\Controller\ContentElement\GooglemapsEmbedController: ~
  tdoescher\GooglemapsBundle\Controller\ContentElement\GooglemapsHTMLController: ~
